name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_project:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y nodejs npm
      - name: Build project
        run: npm run build --if-present --skip-tests

  build_image:
    runs-on: self-hosted
    needs: build_project
    steps:
      - name: Build Docker image
        run: docker build -t sakthisiddu1/docker-react:${{ github.run_number }} .

  push_image:
    runs-on: self-hosted
    needs: build_image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image
        run: docker push sakthisiddu1/docker-react:${{ github.run_number }}

  deploy:
    runs-on: self-hosted
    needs: push_image
    steps:
      - name: Deploy to Kubernetes
        run: |
          echo '
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                - name: myapp
                  image: sakthisiddu1/docker-react:${{ github.run_number }}
                  ports:
                  - containerPort: 80
          ' > deployment.yaml

          echo '
          apiVersion: v1
          kind: Service
          metadata:
            name: myapp-service
          spec:
            type: NodePort
            selector:
              app: myapp
            ports:
              - port: 80
                nodePort: 30007
                targetPort: 80
          ' > service.yaml

          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@13.232.58.60 "kubectl apply -f -" < deployment.yaml
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/test.pem ubuntu@13.232.58.60 "kubectl apply -f -" < service.yaml
