name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t ratneshpuskar/docker-react:${{ github.run_number }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ratneshpuskar/docker-react:${{ github.run_number }}

      - name: Deploy to Kubernetes
        env:
          KUBERNETES_INSTANCE_IP: ${{ secrets.KUBERNETES_INSTANCE_IP }}
        run: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: docker-react-deployment
            labels:
              app: docker-react
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: docker-react
            template:
              metadata:
                labels:
                  app: docker-react
              spec:
                containers:
                - name: docker-react
                  image: ratneshpuskar/docker-react:${{ github.run_number }}
                  ports:
                  - containerPort: 80
          " > deployment.yaml

          echo "
          apiVersion: v1
          kind: Service
          metadata:
            name: docker-react-service
          spec:
            selector:
              app: docker-react
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80
              nodePort: 30007
            type: NodePort
          " > service.yaml

          ssh -i /var/test.pem -o StrictHostKeyChecking=no ubuntu@13.203.9.97 "kubectl apply -f -" < deployment.yaml
          ssh -i /var/test.pem -o StrictHostKeyChecking=no ubuntu@13.203.9.97 "kubectl apply -f -" < service.yaml
